# Generated by Django 4.0.5 on 2022-08-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('DOB', models.DateField(blank=True)),
                ('blood_group', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('upcoming_appointment', models.DateTimeField(blank=True, null=True)),
                ('sent_mail', models.BooleanField(default=False)),
            ],
        ),
    ]
