# Generated by Django 4.0.5 on 2022-08-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='sent_mail',
            field=models.BooleanField(default=True),
        ),
    ]
